package setup

import (
	"fmt"

	"github.com/finnwastakenwastaken/pelican-auto-proxy/agent/internal/wg"
)

// Paths this command owns. Everything the agent writes lives under one of
// these two trees, which is what makes "autoproxy-agent uninstall" a complete
// list rather than a hunt.
const (
	EtcDir     = "/etc/autoproxy"
	StateDir   = "/var/lib/autoproxy"
	TLSDir     = EtcDir + "/tls"
	CertPath   = TLSDir + "/agent.crt"
	KeyPath    = TLSDir + "/agent.key"
	EnvPath    = EtcDir + "/agent.env"
	RulesPath  = EtcDir + "/rules.nft"
	CodePath   = EtcDir + "/vps-code"
	WGDir      = "/etc/wireguard"
	WGConf     = WGDir + "/wg0.conf"
	WGKey      = WGDir + "/autoproxy-server.key"
	WGPub      = WGDir + "/autoproxy-server.pub"
	NftConf    = "/etc/nftables.conf"
	NftBackup  = "/etc/nftables.conf.pre-autoproxy"
	SysctlConf = "/etc/sysctl.d/99-autoproxy.conf"
	UnitPath   = "/etc/systemd/system/autoproxy-agent.service"
	BinPath    = "/usr/local/bin/autoproxy-agent"
	WGIface    = "wg0"
)

// NftMarker identifies an /etc/nftables.conf that we generated. Without it in
// an existing file, setup refuses to overwrite: that file is somebody else's
// firewall until proven otherwise.
const NftMarker = "autoproxy-managed"

// baseNft is the base firewall. @SSH_PORT@, @WG_PORT@ and @API_PORT@ are
// substituted at install time.
//
// There is deliberately NO forward chain here. The agent's table
// (inet autoproxy_rules) owns the forward hook and its policy. nftables
// requires every base chain at a hook to accept, so a forward chain in both
// files would split ownership of forwarding across two writers.
const baseNft = `#!/usr/sbin/nft -f
# autoproxy-managed: generated by "autoproxy-agent setup" -- do not edit by hand.
#
# Pelican Auto Proxy base ruleset.
#
# We never "flush ruleset" here: that would also wipe the agent-owned
# inet autoproxy_rules table, closing every game port until the next sync.
# Instead we declare-then-delete only our own table by exact name, so
# re-applying this file never touches the agent's rules.

table inet autoproxy_base {}
delete table inet autoproxy_base

table inet autoproxy_base {
	chain input {
		type filter hook input priority filter; policy drop;

		iif lo accept
		ct state established,related accept
		ct state invalid drop

		ip protocol icmp accept
		ip6 nexthdr icmpv6 accept

		# SSH. Detected from sshd at install time.
		tcp dport @SSH_PORT@ accept

		# WireGuard: the clients dial in here.
		udp dport @WG_PORT@ accept

		# Agent API. Reachable from anywhere because the Pelican panel may be
		# anywhere; it is protected by TLS and a bearer token, not by address.
		tcp dport @API_PORT@ accept
	}

	chain output {
		type filter hook output priority filter; policy accept;
	}
}

# Guard: /etc/autoproxy/rules.nft must always exist. nftables aborts loading
# this ENTIRE file when an include target is absent, which would leave the box
# with no firewall at boot -- not just a missing agent table. Setup creates an
# empty placeholder so the include always resolves.
include "/etc/autoproxy/rules.nft"
`

// emptyRules is the placeholder the include depends on before the agent has
// ever applied anything.
const emptyRules = `#!/usr/sbin/nft -f
# Placeholder written by "autoproxy-agent setup". The agent overwrites this on
# every apply.
table inet autoproxy_rules {}
`

// unitFile is the systemd unit. The hardening is deliberate and each line is
// explained where it is not obvious.
const unitFile = `[Unit]
Description=Pelican Auto Proxy agent (VPS side: nftables owner and control API)
Documentation=https://github.com/finnwastakenwastaken/pelican-auto-proxy
# After+Wants rather than Requires: if wg0 is down we still want the agent to
# start, listen and report the problem through /v1/status, rather than being
# blocked from starting at all.
After=network-online.target wg-quick@wg0.service
Wants=network-online.target
# No start-rate limit: a tunnel that comes up late must not put the unit in
# "failed" permanently, where nobody notices until a sync stops working.
StartLimitIntervalSec=0

[Service]
Type=simple
ExecStart=/usr/local/bin/autoproxy-agent run
EnvironmentFile=/etc/autoproxy/agent.env
Restart=always
RestartSec=2

# Root with a bounding set of exactly CAP_NET_ADMIN, rather than a dedicated
# user: the agent needs CAP_NET_ADMIN to drive nft, wg and ip, and it also has
# to read /etc/autoproxy/agent.env (the bearer token and the TLS key) and write
# /etc/autoproxy/rules.nft and /var/lib/autoproxy. This is the simplest thing
# that covers all three and still keeps the blast radius at "network admin".
User=root
AmbientCapabilities=CAP_NET_ADMIN
CapabilityBoundingSet=CAP_NET_ADMIN

NoNewPrivileges=yes
ProtectSystem=strict
ReadWritePaths=/etc/autoproxy /var/lib/autoproxy
PrivateTmp=yes
ProtectHome=yes
ProtectKernelTunables=yes
ProtectControlGroups=yes
RestrictSUIDSGID=yes
StandardOutput=journal

# ProtectSystem=strict makes the filesystem outside ReadWritePaths read-only,
# not hidden: /usr/sbin/nft, /usr/bin/wg and /sbin/ip stay executable.

[Install]
WantedBy=multi-user.target
`

// WG0Conf renders /etc/wireguard/wg0.conf.
//
// There are deliberately NO hooks (PostUp/PreUp/...): wg-quick treats a
// failing hook as fatal and deletes the interface it has just created, so one
// sysctl the kernel happens to refuse -- a container, LXC, a locked-down
// provider kernel -- would take the whole tunnel down with a message nobody
// reads. The VPS does not need a loosened rp_filter anyway: every address a
// peer sends from is in its AllowedIPs and therefore routed back down wg0, so
// the strict reverse-path check passes. (The client does need rp_filter=2;
// that is its own business.)
//
// There are also no peers. They are added live by the agent from peers.json;
// two writers on this file is how peers silently disappear after a reboot.
//
// FwMark IS written here, unlike everything else dynamic, because it must be
// true from the instant wg-quick brings the interface up, not from whenever
// the agent next starts. The mark is what tells the peer-routing ip rule
// (see package wg) that a packet is the tunnel's own encrypted transport and
// must therefore consult the main table, not the peer table. If the interface
// came up unmarked and a site peer's lan_cidrs happened to cover that peer's
// own endpoint address, the VPS would route its own handshakes into the
// tunnel it is trying to open, and the tunnel would never come up. The agent
// sets the same mark again on start with "wg set" -- that is what repairs an
// existing install whose wg0.conf predates this -- but the boot path must not
// depend on the agent winning a race with wg-quick.
//
// FwMark is a plain "wg setconf" [Interface] key, not a wg-quick hook, so it
// carries none of the "a failing hook deletes the interface" risk above.
func WG0Conf(tunnelIP string, bits, listenPort int, privateKey string) string {
	return fmt.Sprintf(`# autoproxy-managed: rewritten by "autoproxy-agent setup".
# Peers are NOT listed here. They are added live by the agent from
# /var/lib/autoproxy/peers.json; do not add peers by hand.
[Interface]
Address = %s/%d
ListenPort = %d
PrivateKey = %s
# Marks this interface's own encrypted packets so the "not fwmark %s lookup %s"
# ip rule lets them reach the peer's real endpoint through the main table
# instead of looping back into the tunnel. Do not change it here alone; the
# agent uses the same constant (agent/internal/wg.DefaultFWMark).
FwMark = %s
`, tunnelIP, bits, listenPort, privateKey, wg.DefaultFWMark, wg.DefaultTable, wg.DefaultFWMark)
}

const sysctlFile = `# autoproxy-managed: the VPS routes player traffic into the WireGuard tunnel.
net.ipv4.ip_forward=1
`
